---

name: Integration
on:
  pull_request:
    branches:
      - master
      - development

jobs:

  build_job:

    name: build_job
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Setup go for tests
        uses: actions/setup-go@v1.1.1
        with:
          go-version: '1.13.3' # The Go version to download (if necessary) and

      - name: Build go package
        run: |
          make all

      - name: Run tests
        id: go_run_test
        run: |
          make run

      - name: Docker build
        uses: docker://pasientskyhosting/action-docker-build-push:latest
        with:
          image_name: karstenjakobsen/draft-test
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  dockerfile_lint_job:

    name: dockerfile_lint_job
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: dockerfile-linter
        id: dockerfile-linter
        uses: docker://pasientskyhosting/action-dockerfile-linter:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  golangci_lint_job:

    name: golangci_lint_job
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: golangci-lint
        id: golangci-lint
        uses: docker://pasientskyhosting/action-golangci-lint:latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
