---

name: Integration
on:
  push:
    branches:
    - development
  pull_request:
    branches:
    - master
    - development

jobs:

  docker_build_job:

    name: docker_build_job
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Docker build
        uses: docker://pasientskyhosting/action-docker-build-push:latest
        with:
          image_name: pasientskyhosting/ps-otu-ldap
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  dockerfile_lint_job:

    name: dockerfile_lint_job
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: dockerfile-linter
        id: dockerfile-linter
        uses: docker://pasientskyhosting/action-dockerfile-linter:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  golangci_lint_job:

    name: golangci_lint_job
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: golangci-lint
        id: golangci-lint
        uses: docker://pasientskyhosting/action-golangci-lint:latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  golang_test_job:

    name: golang_test_job
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1      

      - name: Setup go for tests
        uses: actions/setup-go@v1.1.1
        with:
          go-version: '1.12.5' # The Go version to download (if necessary) and 
          
      - name: Run tests
        id: go_run_test
        run: |          
          go run main.go

